config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :actions, only: [:index]
end

  # Defines the root path route ("/")
  # root "posts#index"

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/actions_controller.rb
class ActionsController < ApplicationController

    def index
      @actions = Action.all
    end

    def show
      @action = Action.find(params[:id])
    end

    def new
      @action = Action.new
    end

    def create
      @action = Action.new(action_params)
      @action.save
      redirect_to action_path(@action)
    end

    def edit
      @action = Action.find(params[:id])
    end

    def update
      @action = Action.find(params[:id])
      @action.update(action_params)
      redirect_to action_path(@action)
    end

    def destroy
      @action = Action.find(params[:id])
      @action.destroy
      redirect_to tasks_path(@action)
    end
    private

    def task_params
      params.require(:action).permit(:title, :text)
    end



  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/actions_helper.rb
module ActionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/actions/edit.html.erb
<%= form_with model: @restaurant do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :text %>
  <%= f.text_field :text %>
<% end %>

app/views/actions/index.html.erb
h1>actions</h1>
<ul>
  <% @actions.each do |action| %>
    <li><%= link_to action.title, task_path(task) %></li>
  <% end %>
   <%= link_to "ajouter une action", new_task_path %>
</ul>

app/views/actions/new.html.erb
<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :text %>
  <%= f.text_field :text %>
  <%= f.submit %>
<% end %>

app/views/actions/show.html.erb
<h2><%= @action.title %></h2>
<p><%= @action.text %></p>
<%= link_to "editer", edit_action_path %>


<%= link_to "Delete",
  action_path(@action),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>